routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::prefix('admin')->namespace('Admin')->group(function () {
    Route::any('login', 'UserController@login')->name('admin-login');
    
    Route::group(['middleware' => 'adminAuth'], function(){
    Route::get('/', 'DashboardController@index')->name('admin');
    Route::any('logout', 'UserController@logout')->name('admin-logout');
    Route::get('dashboard', 'DashboardController@index')->name('admin-dashboard');
    
    Route::resource('clients', 'ClientController');
    Route::resource('projects', 'ProjectController');
    Route::resource('companies', 'CompanyController');
    Route::resource('users', 'UserController');
    Route::resource('branches', 'BranchController');
    Route::resource('profiles', 'ProfileController');
    Route::get('getbranches/{id}', 'BranchController@getBranches')->name('admin-ajax-branches');
    Route::get('getclients/{id}', 'ClientController@getClients')->name('admin-ajax-cleints');

    

    Route::bind('page', function($value, $route) {
        return App\Models\Page::find($value);
    });

    Route::resource('pages', 'PageController', [
        'names' => [
            'edit' => 'page.edit',
            'show' => 'page.show',
            'destroy' => 'page.destroy',
            'update' => 'page.update',
            'store' => 'page.store',
            'index' => 'page',
            'create' => 'page.create',
        ]
            ]
    );
     });
});
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

resources/views/admin/include/breadcrumb.blade.php
<!-- BEGIN PAGE HEAD-->
<div class="page-head">
    <!-- BEGIN PAGE TITLE -->
    <div class="page-title">
        <h1>{{$heading_title}}</h1>
    </div>
    <!-- END PAGE TITLE -->
    <!-- BEGIN PAGE TOOLBAR -->
    
    <!-- END PAGE TOOLBAR -->
</div>

resources/views/admin/include/footer.blade.php
<div class="page-footer-inner"> 2018 &copy; LogMyday
    <a target="_blank" href="">StealCoder</a> &nbsp;|&nbsp;
    <a href="" title="" target="_blank">Motifworks</a>
</div>

resources/views/admin/include/header.blade.php
<div class="page-header-inner ">
    <!-- BEGIN LOGO -->
    <div class="page-logo">
        <a href="{{route('admin')}}">
            <img src="{{asset('assets')}}/images/logo/logo.png" alt="logo" class="logo-default" width="200px;"/> </a>
        <!--<div class="menu-toggler sidebar-toggler">
             DOC: Remove the above "hide" to enable the sidebar toggler button on header 
        </div>-->
    </div>
    <!-- END LOGO -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
    <!-- END RESPONSIVE MENU TOGGLER -->

    <!-- BEGIN PAGE TOP -->
    <div class="page-top">
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="page-actions">
            <div class="btn-group">
                <a href="{{route('companies.create')}}" class="btn red-haze btn-sm">
                    <i class="fa fa-plus-circle"></i>
                    <span class="hidden-sm hidden-xs">Add Company</span>
                </a>
            </div>
        </div>
        <div class="top-menu">

            <ul class="nav navbar-nav pull-right">
                <!-- END TODO DROPDOWN -->
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user dropdown-dark">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <span class="username username-hide-on-mobile">     
                            @if(Auth::user() && Auth::user()->username)
                            {{Auth::user()->username}}
                            @else
                            User
                            @endif
                        </span>
                        <!-- DOC: Do not remove below empty space(&nbsp;) as its purposely used -->
                        <img alt="" class="img-circle" src="{{asset('assets')}}/layouts/layout4/img/avatar9.jpg" /> </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>
                            <a href="{{route('profiles.index')}}">
                                <i class="icon-user"></i> My Profile </a>
                        </li>
                        <li>
                            <a href="app_todo_2.html">
                                <i class="icon-rocket"></i> My Tasks
                                <span class="badge badge-success"> 7 </span>
                            </a>
                        </li>
                        <li class="divider"> </li>
                        <li>
                            <a href="{{route('admin-logout')}}">
                                <i class="icon-key"></i> Log Out </a>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END PAGE TOP -->
</div>

resources/views/admin/include/sidebar.blade.php
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu   " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
            <li class="nav-item {{ Request::path() == 'admin' ? 'active' : '' }}">
                <a href="{{route('admin')}}" class="nav-link ">
                    <i class="fa fa-2x fa-dashboard"></i>
                    <span class="title">Dashboard</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="nav-item {{ Request::segment(2) == 'companies' ? 'active' : '' }}">
                <a href="{{route('companies.index')}}" class="nav-link ">
                    <i class="fa fa-2x fa-university"></i>
                    <span class="title">Company</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="nav-item {{ Request::segment(2) == 'branches' ? 'active' : '' }}">
                <a href="{{route('branches.index')}}" class="nav-link ">
                    <i class="fa fa-2x fa-building-o"></i>
                    <span class="title">Branches</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="nav-item {{ Request::segment(2) == 'users' ? 'active' : '' }}">
                <a href="{{route('users.index')}}" class="nav-link ">
                    <i class="fa fa-2x fa-slideshare"></i>
                    <span class="title">Users</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="nav-item {{ Request::segment(2) == 'clients' ? 'active' : '' }}">
                <a href="{{route('clients.index')}}" class="nav-link ">
                    <i class="fa fa-2x fa-users"></i>
                    <span class="title">Clients</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="nav-item {{ Request::segment(2) == 'projects' ? 'active' : '' }}">
                <a href="{{route('projects.index')}}" class="nav-link ">
                    <i class="fa fa-2x fa-cubes"></i>
                    <span class="title">Projects</span>
                    <span class="selected"></span>
                </a>
            </li>
            <li class="nav-item {{ Request::segment(2) == 'pages' ? 'active' : '' }}">
                <a href="{{route('page')}}" class="nav-link ">
                    <i class="fa fa-2x fa-file-text-o"></i>
                    <span class="title">Static Content</span>
                    <span class="selected"></span>
                </a>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>